name: ML CI

on:
  push:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  ml-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug OIDC claims
        shell: bash
        run: |
          response=$(curl -sS \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com")

          token=$(echo "$response" | jq -r '.value')

          payload=$(echo "$token" | cut -d '.' -f2 | base64 -d 2>/dev/null)

          echo "$payload" | jq '{iss, sub, aud, repository, ref, event_name, repository_owner}'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::205950089606:role/GitHubActions-ML-Iris
          aws-region: eu-north-1